@startuml BeatyOn


entity Cliente {
    *id : string <<generated>>
    --
    *enderecoId : string <<FK>>
    *nome : string
    *email : string
    *senha : string
    *telefone : string
    lat : number
    long : number
}

entity Endereco {
    *id : string <<generated>>
    --
    *entidadeId : string <<FK>>
    logradouro : string
    numero : string
    complemento : string
    bairro : string
    cidade : string
    estado : string
    cep : string
    long : number
    lat : number
}

entity Estabelecimento {
    *id : string <<generated>>
    --
    *enderecoId : string <<FK>>
    *nome : string
    *descricao : string
    *telefone : string
    *email : string
    *senha : string
    cnpj : string
}

entity CategoriaServico{
    *id : string <<generated>>
    --
    *nome : string
    *descricao : string
}

entity ServicoEstabelecimento{
    *id : string <<generated>>
    --
    *estabelecimentoId : string <<FK>>
    *categoriaServicoId : string <<FK>>
    *nome : string
    *descricao : string
    *valor : number
    *tempo : number
}

entity Agendamento{
    *uuid : string <<generated>>
    --
    *clienteId : string <<FK>>
    *estabelecimentoId : string <<FK>>
    *profissionalId : string <<FK>>
    *servicoId : string <<FK>>
    *data : string
    *hora : string
    *status : string
}

entity HorarioFuncionamento{
    *id : string <<generated>>
    --
    *estabelecimentoId : string <<FK>>
    *diaSemana : string
    *horaInicio : string
    *horaFim : string
}

entity Profissional{
    *id : string <<generated>>
    --
    *estabelecimentoId : string <<FK>>
    *nome : string
    *descricao : string
    *telefone : string
    *email : string
}

entity ProfissionalPorServicoEstabelecimento{
    *id : string <<generated>>
    --
    *profissionalId : string <<FK>>
    *servicoEstabelecimentoId : string <<FK>>
}

entity Favorito{
    *id : string <<generated>>
    --
    *clienteId : string <<FK>>
    *estabelecimentoId : string <<FK>>
}

entity Galeria {
    *id : string <<generated>>
    --
    *estabelecimentoId : string <<FK>>
    *url : string
}

Cliente ||-up-o{ Favorito
Estabelecimento ||-down-o{ Favorito
Estabelecimento ||-up-o{ Galeria
Agendamento }o-up-|| Profissional
Agendamento }o--|| ServicoEstabelecimento
Agendamento }o--|| Cliente
Estabelecimento ||-down-|| Endereco
Estabelecimento ||-up-o{ Profissional
Estabelecimento ||--o{ ServicoEstabelecimento

Cliente ||-right-|| Endereco
TipoServico ||--o{ ServicoEstabelecimento
Estabelecimento ||--o{ HorarioFuncionamento
Profissional ||-left-o{ ProfissionalPorServicoEstabelecimento
ServicoEstabelecimento ||--o{ ProfissionalPorServicoEstabelecimento


@enduml